### ISSUE TITLE
Unhandled Exception: Bad state: No element

### ISSUE THREAD

**Issue by IhabZaidi** [FilledStacks/expression-ui#23]
I tried multiple time to just test the pure example code from this repo but always ended with error!
basically i download the example code and add the exp package to it like that :
```
dependencies:
  flutter:
    sdk: flutter
  responsive_builder: ^0.7.0
  stacked: ^3.4.0
  stacked_services: ^1.1.0

  expression_ui:
    path: expression-ui
```
and after run/restart issue (tested on emulator and real device) :

```
E/flutter (23338): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: No element
E/flutter (23338): #0      Iterable.first (dart:core/iterable.dart:643:7)
E/flutter (23338): #1      BaseExpressionView.onRiveFileInitialized (package:expression_ui/src/expression_widgets/base_expression_view.dart:117:14)
E/flutter (23338): #2      BaseExpressionView.build.<anonymous closure> (package:expression_ui/src/expression_widgets/base_expression_view.dart:65:29)
E/flutter (23338): #3      RiveAnimationState._init (package:rive/src/widgets/rive_animation.dart:323:20)
E/flutter (23338): #4      RiveAnimationState._configure (package:rive/src/widgets/rive_animation.dart:212:5)
E/flutter (23338): <asynchronous suspension>
E/flutter (23338): 
```

 i will try later to create a brand new stacked app with custom rive artboard and attach the result
